### ISSUE TITLE
This engine has support for Symbol.toStringTag, but Float32Array does not have the property! Please report this

### ISSUE THREAD

**Issue by zba** [inspect-js/which-typed-array#46] opened 2020-11-24 07:16 UTC
Hi, I got this error in very old chromium version Version 46.0.2490.0 (windows) while checking compatibility of old clients.
Seems it started to happen after webpack5 upgrade. 
Can you please advice what it means and what could be a reason. 

The stack shows that it caused  by the line:

```var inherits = require('util').inherits;```

in our code.

**Comment by ljharb** [comment] 2020-11-24 21:27
What likely happened is that webpack 5 is broken, because it no longer polyfills node core modules by default.

I believe you’ll need to manually use the ProvidePlugin to polyfill the `util` module, or downgrade to webpack 4 (which I’d recommend).

I will definitely check that version of chromium to verify if there’s a bug in this library, regardless. It would be very helpful if you could verify, in the console of that browser, that Symbol.toStringTag exists and is a symbol, and that Float32Array.prototype[Symbol.toStringTag] is indeed undefined?

**Comment by zba** [comment] 2020-11-25 06:00
Yes, Symbol.toStringTag exists and Float32Array.prototype[Symbol.toStringTag]  does not exist.
 I also made a bug to core-js https://github.com/zloirock/core-js/issues/890

**Comment by ljharb** [comment] 2020-11-25 06:05
Thanks! That does seem fixable.

**Comment by ljharb** [comment] 2020-11-25 06:07
Hmm - in Chrome 46 on Windows, `Symbol.toStringTag` is `undefined`. If you're using core-js, perhaps it's installing a Symbol sham (since Symbol can't be truly polyfilled) - what is `typeof Symbol.toStringTag` in Chromium 46 on Windows?

If it's not `symbol`, then could you provide the exact core-js version you're using? It's possible I'll have to work around core-js, and equally possible it'll just be an unsupported scenario.

**Comment by zba** [comment] 2020-11-25 06:08
I using core-js for polifilling it

**Comment by zba** [comment] 2020-11-25 06:09
let me try to make minimal example, so we can repeat problem easer.

**Comment by ljharb** [comment] 2020-11-25 06:16
Which version of core-js?

**Comment by zba** [comment] 2020-11-25 06:21
core-js@3.7.0

**Comment by ljharb** [comment] 2020-11-25 15:28
So what is `typeof Symbol.toStringTag` in that browser?

The code that throws this error shouldn't be possible to enter unless there's real Symbols available.

**Comment by zba** [comment] 2020-11-26 04:46
it is "symbol" I suspect that Symbol.toStringTag key and Symbol.toStringTag in Float32Array.prototype key are different symbols, but I can't get this key, so can't compare. While I tried to make minimal reproduce, I found that everything works as expected, so probably problem somewhere different place. Also there is difference, that modules form core-js like es.typed-array not in sourcemap of my product code, while they are exist in my try for minimal reproduce.

**Comment by zba** [comment] 2020-11-26 04:55
Yes, they are a different symbols:

**`Object.getOwnPropertySymbols(Float32Array.prototype)[0]`**
`Symbol(Symbol.toStringTag)`
**`Object.getOwnPropertySymbols(Float32Array.prototype)[0] === Symbol.toStringTag`**
`false`

**Comment by zba** [comment] 2020-11-26 05:31
So I found, that this browser has `Float32Array`(and others) with `Symbol.toStringTag` support, but initially does not have `Symbol.toStringTag` property of `Symbol`. So the error happen because something created this Symbol, but o'c as they not get it from prototype it is a different ssymbol,   so I patched it with the following:

```
(function() {
	if (Symbol && typeof Symbol.toStringTag === 'symbol' || !Float32Array) {
		return;
	}
	var s=Object.getOwnPropertySymbols(Float32Array.prototype).filter(function(s) {return s.toString().match('Symbol.toStringTag')})[0]
	if (s) {Symbol.toStringTag = s }
})();
```

in very begining of execution. 

However I still not understand, how my minimal example works without such patch...

**Comment by ljharb** [comment] 2020-11-26 22:57
@zba so, the implication from the linked core-js issue is that this is caused by an incorrect core-js load order. If you're not using core-js, presumably everything works?

**Comment by ljharb** [comment] 2020-12-04 06:44
I'm going to close this, but will immediately reopen if there's something actionable this package needs to do.

**Closed as completed by ljharb** 2020-12-04 06:44 UTC
